# Generated by Django 4.0.5 on 2022-06-18 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_rename_pass_login_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='password',
            new_name='passwords',
        ),
    ]
